name: Build and Push Image to ECR Registry

on:
  workflow_dispatch:
    inputs:
      release_version:
        description: 'Image version (e.g., 0.1.1)'
        type: string
        required: true
      region:
        description: 'AWS Region'
        type: string
        required: true
        default: us-east-1

permissions:
  id-token: write
  contents: read

jobs:
  package-and-push-chart:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set IAM role to assume
        id: set-role
        run: |
          echo "role=${{ secrets.SAAS_AWS_DEPLOY_ROLE_ARN }}" >> $GITHUB_OUTPUT

      - name: Assume IAM Role
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ steps.set-role.outputs.role }}
          aws-region: ${{ inputs.region }}
          role-session-name: ecr-build-session

      - name: Login to Amazon ECR (Helm OCI)
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        with:
          registries: "897729109735"

      - name: Build,tag and push image
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ steps.login-ecr.outputs.registry }}/jarvis/mssql_mcp_server:${{ github.sha }}
            ${{ steps.login-ecr.outputs.registry }}/jarvis/mssql_mcp_server:latest
          provenance: false